const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={blue:document.querySelector('#blueScore'),red:document.querySelector('#redScore'),timer:document.querySelector('#timer'),health:document.querySelector('#healthBar'),healthText:document.querySelector('#healthText'),ammo:document.querySelector('#ammo'),feed:document.querySelector('#feed'),message:document.querySelector('#message'),overlay:document.querySelector('#startScreen')};
const W=1280,H=720,keys={},mouse={x:W/2,y:H/2,down:false}; let running=false,last=0,timeLeft=180,blueScore=0,redScore=0,muted=false,shake=0;
const obstacles=[{x:280,y:90,w:150,h:65},{x:850,y:95,w:160,h:65},{x:545,y:260,w:190,h:70},{x:120,y:315,w:150,h:58},{x:1010,y:330,w:150,h:58},{x:300,y:535,w:155,h:62},{x:820,y:540,w:155,h:62}];
const spawn={blue:[{x:115,y:125},{x:100,y:360},{x:130,y:595}],red:[{x:1165,y:125},{x:1180,y:360},{x:1150,y:595}]};
let agents=[],bullets=[],particles=[];
function makeAgent(team,index,player=false){const s=spawn[team][index];return {team,index,player,x:s.x,y:s.y,r:16,hp:100,alive:true,respawn:0,angle:team==='blue'?0:Math.PI,speed:player?185:125,cooldown:Math.random(),ammo:12,reload:0,name:player?'你':`${team==='blue'?'蓝':'红'}队 ${index+1}`,target:null,strafe:Math.random()<.5?-1:1};}
function reset(){agents=[makeAgent('blue',0,true),makeAgent('blue',1),makeAgent('blue',2),makeAgent('red',0),makeAgent('red',1),makeAgent('red',2)];bullets=[];particles=[];timeLeft=180;blueScore=redScore=0;updateUI();}
const player=()=>agents[0]; const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function blocked(x,y,r=16){return x<r+20||x>W-r-20||y<r+20||y>H-r-20||obstacles.some(o=>x+r>o.x&&x-r<o.x+o.w&&y+r>o.y&&y-r<o.y+o.h);}
function move(a,dx,dy,dt){const l=Math.hypot(dx,dy)||1,step=a.speed*dt;let nx=a.x+dx/l*step,ny=a.y+dy/l*step;if(!blocked(nx,a.y,a.r))a.x=nx;if(!blocked(a.x,ny,a.r))a.y=ny;}
function shoot(a){if(!a.alive||a.cooldown>0||a.reload>0||a.ammo<=0)return;a.cooldown=a.player?.14:.42+Math.random()*.16;a.ammo--;const spread=a.player?.035:.1;const angle=a.angle+(Math.random()-.5)*spread;bullets.push({x:a.x+Math.cos(angle)*23,y:a.y+Math.sin(angle)*23,vx:Math.cos(angle)*650,vy:Math.sin(angle)*650,team:a.team,owner:a,life:1.2});for(let i=0;i<5;i++)particles.push({x:a.x+Math.cos(angle)*24,y:a.y+Math.sin(angle)*24,vx:Math.cos(angle)*Math.random()*70+(Math.random()-.5)*40,vy:Math.sin(angle)*Math.random()*70+(Math.random()-.5)*40,life:.18,color:'#ffd86b'});if(a.player)shake=2; if(a.ammo===0)reload(a);}
function reload(a){if(a.reload||a.ammo===12)return;a.reload=1.15;}
function kill(victim,killer){victim.alive=false;victim.respawn=2.7;killer.team==='blue'?blueScore++:redScore++;addFeed(killer,victim);for(let i=0;i<16;i++)particles.push({x:victim.x,y:victim.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:.5,color:victim.team==='blue'?'#1ed6ff':'#ff4264'});updateUI();if(blueScore>=20||redScore>=20)endGame();}
function addFeed(k,v){const el=document.createElement('div');el.innerHTML=`<b>${k.name}</b>　⌁　${v.name}`;el.style.borderColor=k.team==='blue'?'#1ed6ff':'#ff4264';ui.feed.prepend(el);setTimeout(()=>el.remove(),3200);while(ui.feed.children.length>4)ui.feed.lastChild.remove();}
function updatePlayer(dt){const p=player();if(!p.alive)return;let dx=(keys.KeyD?1:0)-(keys.KeyA?1:0),dy=(keys.KeyS?1:0)-(keys.KeyW?1:0);if(dx||dy)move(p,dx,dy,dt);p.angle=Math.atan2(mouse.y-p.y,mouse.x-p.x);if(mouse.down)shoot(p);}
function updateAI(a,dt){if(!a.alive)return;const enemies=agents.filter(e=>e.alive&&e.team!==a.team).sort((x,y)=>dist(a,x)-dist(a,y));a.target=enemies[0];if(!a.target)return;const d=dist(a,a.target),ang=Math.atan2(a.target.y-a.y,a.target.x-a.x);a.angle=ang;let dx=Math.cos(ang),dy=Math.sin(ang);if(d<210){dx=-dx*.4+Math.cos(ang+Math.PI/2)*a.strafe;dy=-dy*.4+Math.sin(ang+Math.PI/2)*a.strafe}else if(d<380){dx=Math.cos(ang+Math.PI/2)*a.strafe;dy=Math.sin(ang+Math.PI/2)*a.strafe}move(a,dx,dy,dt);if(d<500)shoot(a);}
function update(dt){if(!running)return;timeLeft-=dt;if(timeLeft<=0)endGame();updatePlayer(dt);agents.forEach(a=>{a.cooldown=Math.max(0,a.cooldown-dt);if(a.reload>0){a.reload-=dt;if(a.reload<=0)a.ammo=12}if(!a.alive){a.respawn-=dt;if(a.respawn<=0){const s=spawn[a.team][a.index];Object.assign(a,{x:s.x,y:s.y,hp:100,alive:true,ammo:12,reload:0})}}else if(!a.player)updateAI(a,dt)});bullets.forEach(b=>{b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(blocked(b.x,b.y,3))b.life=0;for(const a of agents){if(b.life>0&&a.alive&&a.team!==b.team&&dist(a,b)<a.r+3){a.hp-=25;b.life=0;if(a.hp<=0)kill(a,b.owner)}}});bullets=bullets.filter(b=>b.life>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.93;p.vy*=.93;p.life-=dt});particles=particles.filter(p=>p.life>0);shake*=.84;updateUI();}
function drawGrid(){ctx.fillStyle='#0a141b';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#142832';ctx.lineWidth=1;for(let x=0;x<W;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}ctx.strokeStyle='#1a3541';ctx.setLineDash([12,12]);ctx.strokeRect(35,35,W-70,H-70);ctx.setLineDash([]);ctx.fillStyle='#11242c';ctx.fillRect(W/2-2,35,4,H-70);}
function drawObstacle(o){ctx.shadowColor='#000';ctx.shadowBlur=16;ctx.fillStyle='#172832';ctx.fillRect(o.x,o.y,o.w,o.h);ctx.shadowBlur=0;ctx.strokeStyle='#36505b';ctx.lineWidth=3;ctx.strokeRect(o.x,o.y,o.w,o.h);ctx.fillStyle='#1b343e';ctx.fillRect(o.x+9,o.y+9,o.w-18,8);ctx.strokeStyle='#263e48';for(let x=o.x+18;x<o.x+o.w;x+=28){ctx.beginPath();ctx.moveTo(x,o.y+22);ctx.lineTo(x-18,o.y+o.h);ctx.stroke()}}
function drawAgent(a){if(!a.alive)return;const c=a.team==='blue'?'#20d9ff':'#ff4264';ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);ctx.shadowColor=c;ctx.shadowBlur=13;ctx.fillStyle=c;ctx.beginPath();ctx.arc(0,0,a.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#071017';ctx.beginPath();ctx.arc(0,0,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ccecff';ctx.fillRect(5,-4,25,8);ctx.fillStyle=c;ctx.fillRect(22,-6,15,12);ctx.restore();ctx.fillStyle='#071017';ctx.fillRect(a.x-20,a.y-29,40,4);ctx.fillStyle=c;ctx.fillRect(a.x-20,a.y-29,40*a.hp/100,4);if(a.player){ctx.strokeStyle='#fff';ctx.lineWidth=1;ctx.beginPath();ctx.arc(a.x,a.y,22,0,Math.PI*2);ctx.stroke();}}
function draw(){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);drawGrid();obstacles.forEach(drawObstacle);bullets.forEach(b=>{ctx.strokeStyle=b.team==='blue'?'#75edff':'#ff91a5';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x,b.y);ctx.lineTo(b.x-b.vx*.018,b.y-b.vy*.018);ctx.stroke()});agents.forEach(drawAgent);particles.forEach(p=>{ctx.globalAlpha=clamp(p.life*3,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x-2,p.y-2,4,4)});ctx.globalAlpha=1;ctx.restore();}
function updateUI(){ui.blue.textContent=blueScore;ui.red.textContent=redScore;const t=Math.max(0,Math.ceil(timeLeft));ui.timer.textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;const p=player();ui.health.style.width=`${Math.max(0,p?.hp||0)}%`;ui.healthText.textContent=Math.max(0,p?.hp||0);ui.ammo.textContent=p?.reload>0?'··':p?.ammo??12;}
function endGame(){if(!running)return;running=false;ui.message.textContent=blueScore===redScore?'平局':blueScore>redScore?'任务完成 · 蓝队胜利':'任务失败 · 红队胜利';setTimeout(()=>{ui.overlay.classList.remove('hidden');document.querySelector('#startBtn').innerHTML='再次出击 <span>→</span>'},1000)}
function loop(now){const dt=Math.min((now-last)/1000,.033)||0;last=now;update(dt);draw();requestAnimationFrame(loop)}
function position(e){const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*W;mouse.y=(e.clientY-r.top)/r.height*H}
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload(player())});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('mousemove',position);canvas.addEventListener('mousedown',e=>{position(e);mouse.down=true});addEventListener('mouseup',()=>mouse.down=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.querySelector('#startBtn').onclick=()=>{reset();running=true;ui.message.textContent='';ui.overlay.classList.add('hidden')};document.querySelector('#reloadBtn').onclick=()=>reload(player());document.querySelector('#soundBtn').onclick=e=>{muted=!muted;e.currentTarget.textContent=muted?'×':'♪'};document.querySelector('#fireBtn').onpointerdown=()=>mouse.down=true;document.querySelector('#fireBtn').onpointerup=()=>mouse.down=false;
const joy=document.querySelector('#joystick'),nub=joy.querySelector('i');joy.addEventListener('pointermove',e=>{if(!e.buttons)return;const r=joy.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2);keys.KeyA=dx<-12;keys.KeyD=dx>12;keys.KeyW=dy<-12;keys.KeyS=dy>12;nub.style.transform=`translate(${clamp(dx,-25,25)}px,${clamp(dy,-25,25)}px)`});joy.addEventListener('pointerup',()=>{keys.KeyA=keys.KeyD=keys.KeyW=keys.KeyS=false;nub.style.transform='' });
reset();requestAnimationFrame(loop);
